repos:
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.8
  hooks:
    - id: bandit

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: end-of-file-fixer
    - id: check-added-large-files
      args:
        - "--maxkb=2000"
    - id: pretty-format-json
      args:
        - "--autofix"

- repo: https://github.com/ambv/black
  rev: 24.2.0
  hooks:
    - id: black
      args:
        - --line-length=88
        - --include='\.pyi?$'
      language_version: python3.11


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
    - id: mypy
      additional_dependencies:
        - 'pydantic'

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.2
  hooks:
    - id: ruff
      args:
        - --fix
